name: shop_sip
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  http: ^0.13.6
  go_router: ^10.1.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  equatable: ^2.0.5
  google_sign_in: ^6.1.5
  bloc_test: ^9.1.4
  mockito: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/Images/
  fonts:
    - family: SFPro
      fonts:
        - asset: fonts/SF-Pro-Text-Black.otf
        - asset: fonts/SF-Pro-Text-Bold.otf
        - asset: fonts/SF-Pro-Text-Light.otf
        - asset: fonts/SF-Pro-Text-Medium.otf
        - asset: fonts/SF-Pro-Text-Regular.otf
        - asset: fonts/SF-Pro-Text-SemiboldItalic.otf
        - asset: fonts/SF-Pro-Text-Thin.otf

